# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Keun.es
email: keunes@mailbox.org
description: >- # this means to ignore newlines until "baseurl:"
  Non-code contributor to AntennaPod &amp; podcasting enthusiast, 🏳️‍🌈, communication officer in education sector, 90's kid, 🇳🇱-🇪🇺, environmentalist. This is my digital home.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keun.es" # the base hostname & protocol for your site, e.g. http://example.com
repository: Keunes/keun.es     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
github_username:  keunes
remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
theme: portfolyou-jekyll-theme
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# FROM PORTFOLYOU THEME #
### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  
  ### Author Info ###
author:
  name              : keunes
  image             : https://avatars.githubusercontent.com/u/11229646
# behance           : your_username
# dribbble          : your_username
# email             : username@domain.com
# facebook          : your_username
  github            : keunes
  gitlab            : keunes
# instagram         : your_username
# kaggle            : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  mastodon          : mastodon.social/@keunes
  mastodon_user     : keunes
  mastodon_server   : mastodon.social # instance domain without protocol (e.g. mastodon.social)

### Posts ###
permalink: /blog/:year/:month/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:title

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - pages/about.md
  
### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

